package com.midlane.project_management_tool_user_service.model;

public enum ActionType {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTRATION,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    MFA_ENABLED,
    MFA_DISABLED,
    PROFILE_UPDATE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    SESSION_CREATED,
    SESSION_EXPIRED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    DATA_ACCESS,
    DATA_MODIFICATION,
    SECURITY_VIOLATION
}
